### ISSUE TITLE
Create a function to extract 'n' number of colors from an image

### ISSUE THREAD

**Issue by abhinandanwadwa** [abhinandanwadwa/image-color-extractor-npm-package#1]
At v1.1.3, this npm package can only extract one dominant color from the image. Create a new function to extract 'n' number of colors from the image and return it as an array.

**Comment by abhinandanwadwa** [comment]
POST an axios request to /api/getncolors route to receive an array of n colors.

In the body of the POST request, along with the 'imageURI', pass 'numberOfColors' argument as the number of colors the request wants to extract

**Comment by Hartaj-Singh-Dev** [comment]
Hey , does this issue still persist ?

**Comment by abhinandanwadwa** [comment]
@Hartaj-Singh-Dev Yes
